# Generated by Django 3.2.19 on 2023-05-24 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_voetballers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voetballers',
            new_name='Voetbalspeler',
        ),
    ]
