# Generated by Django 3.2.19 on 2023-05-24 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_voetballers_voetbalspeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspeler',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
