# Generated by Django 3.2.19 on 2023-05-24 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_voetbalspeler_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voetbalspeler',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
